import type { Locale } from "@/shared/config/site";

export const TREND_COPY = {
  en: {
    dailyTitle: "DAILY TREND TEST",
    comparisons: "5 COMPARISONS",
    known: "KNOWN",
    unknown: "UNKNOWN",
    higher: "HIGHER",
    lower: "LOWER",
    next: "NEXT ROUND",
    finish: "FINISH TEST",
    fieldRecord: "FIELD RECORD",
    currentStreak: "CURRENT STREAK",
    days: "DAYS",
    shareResult: "SHARE RESULT",
    practiceMode: "PRACTICE MODE",
    dailyMode: "DAILY MODE",
    chooseCategory: "CHOOSE CATEGORY",
    score: "SCORE",
    best: "BEST",
    correct: "CORRECT",
    incorrect: "INCORRECT",
    complete: "FIELD TEST COMPLETE",
    completeBody: "Today's result is saved in this browser.",
    practiceOver: "PRACTICE RUN COMPLETE",
    playAgain: "PLAY AGAIN",
    shared: "Result shared.",
    copied: "Result copied.",
    shareUnavailable: "Sharing is unavailable in this browser.",
    source: "DATA SOURCE",
    gameGuideTitle: "HOW TO PLAY",
    gameGuide:
      "Compare the known value with the hidden item. Choose higher or lower, complete five daily rounds, and return tomorrow to extend your streak.",
    dataGuideTitle: "ABOUT THE DATA",
    dataGuide:
      "Values are fixed snapshots from the source linked in each round. Definitions and update dates can differ by category.",
    keyboard: "KEYBOARD: H / L",
    rounds: "ROUNDS",
  },
  ko: {
    dailyTitle: "오늘의 트렌드 테스트",
    comparisons: "5번 비교",
    known: "기준값",
    unknown: "미지값",
    higher: "더 높다",
    lower: "더 낮다",
    next: "다음 라운드",
    finish: "테스트 완료",
    fieldRecord: "기록판",
    currentStreak: "현재 연속 기록",
    days: "일",
    shareResult: "결과 공유",
    practiceMode: "연습 모드",
    dailyMode: "데일리 모드",
    chooseCategory: "카테고리 선택",
    score: "점수",
    best: "최고점",
    correct: "정답",
    incorrect: "오답",
    complete: "오늘의 테스트 완료",
    completeBody: "오늘 결과를 이 브라우저에 저장했습니다.",
    practiceOver: "연습 종료",
    playAgain: "다시 플레이",
    shared: "결과를 공유했습니다.",
    copied: "결과를 복사했습니다.",
    shareUnavailable: "이 브라우저에서는 공유할 수 없습니다.",
    source: "데이터 출처",
    gameGuideTitle: "플레이 방법",
    gameGuide:
      "공개된 기준값과 숨겨진 항목을 비교하세요. 더 높다 또는 더 낮다를 골라 오늘의 5라운드를 완료하고 내일 돌아와 연속 기록을 늘릴 수 있습니다.",
    dataGuideTitle: "데이터 안내",
    dataGuide:
      "각 값은 라운드에 표시된 출처의 고정 스냅샷입니다. 카테고리마다 정의와 갱신일이 다를 수 있습니다.",
    keyboard: "키보드: H / L",
    rounds: "라운드",
  },
  ja: {
    dailyTitle: "デイリートレンドテスト",
    comparisons: "5回比較",
    known: "既知の値",
    unknown: "未知の値",
    higher: "高い",
    lower: "低い",
    next: "次のラウンド",
    finish: "テスト完了",
    fieldRecord: "フィールド記録",
    currentStreak: "現在の連続記録",
    days: "日",
    shareResult: "結果を共有",
    practiceMode: "練習モード",
    dailyMode: "デイリーモード",
    chooseCategory: "カテゴリー選択",
    score: "スコア",
    best: "ベスト",
    correct: "正解",
    incorrect: "不正解",
    complete: "本日のテスト完了",
    completeBody: "本日の結果をこのブラウザに保存しました。",
    practiceOver: "練習終了",
    playAgain: "もう一度",
    shared: "結果を共有しました。",
    copied: "結果をコピーしました。",
    shareUnavailable: "このブラウザでは共有できません。",
    source: "データソース",
    gameGuideTitle: "遊び方",
    gameGuide:
      "既知の値と隠された項目を比較します。高いか低いかを選び、5ラウンドを完了して連続記録を伸ばしましょう。",
    dataGuideTitle: "データについて",
    dataGuide:
      "各値はラウンドに記載した情報源の固定スナップショットです。定義と更新日はカテゴリーごとに異なります。",
    keyboard: "キーボード: H / L",
    rounds: "ラウンド",
  },
} as const satisfies Record<Locale, Record<string, string>>;
