import type {
  AISource,
  AISourceBranding,
  AIContextMeta,
  AICompatibleTool,
} from "./types";

/**
 * AI Source Branding
 */
export const aiSources: Record<AISource, AISourceBranding> = {
  "ai-generated": {
    id: "ai-generated",
    name: "AI-Generated",
    color: "from-purple-500 to-pink-500",
    description: "Code generated by any AI assistant",
  },
  chatgpt: {
    id: "chatgpt",
    name: "ChatGPT",
    color: "from-emerald-500 to-teal-500",
    description: "OpenAI's ChatGPT code output",
  },
  claude: {
    id: "claude",
    name: "Claude",
    color: "from-orange-500 to-amber-500",
    description: "Anthropic's Claude code output",
  },
  copilot: {
    id: "copilot",
    name: "GitHub Copilot",
    color: "from-gray-600 to-gray-800",
    description: "GitHub Copilot suggestions",
  },
  gemini: {
    id: "gemini",
    name: "Gemini",
    color: "from-blue-500 to-indigo-500",
    description: "Google Gemini code output",
  },
  cursor: {
    id: "cursor",
    name: "Cursor AI",
    color: "from-violet-500 to-purple-600",
    description: "Cursor IDE AI suggestions",
  },
};

/**
 * AI-Compatible Tools with Context Metadata
 */
export const aiContextTools: Record<AICompatibleTool, AIContextMeta> = {
  "json-formatter": {
    slug: "json-formatter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "gemini"],
    commonErrors: [
      "Unexpected token in JSON",
      "Single quotes instead of double quotes",
      "Trailing comma in object/array",
      "Unescaped special characters",
      "Missing property quotes",
    ],
    useCases: [
      "Validate ChatGPT-generated API responses",
      "Fix Claude's JSON configuration files",
      "Clean up Copilot's data structures",
    ],
    keywords: [
      "chatgpt json fix",
      "ai json validator",
      "claude json formatter",
      "fix ai json error",
      "copilot json syntax",
    ],
    searchVolume: 8500,
  },

  "jwt-decoder": {
    slug: "jwt-decoder",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Invalid JWT format",
      "Missing JWT segments",
      "Base64 encoding issues",
      "Expired token not detected",
    ],
    useCases: [
      "Decode ChatGPT-generated auth tokens",
      "Verify AI-suggested JWT structures",
      "Debug authentication flows",
    ],
    keywords: [
      "ai jwt decoder",
      "chatgpt jwt token",
      "validate ai auth token",
      "decode jwt online secure",
    ],
    searchVolume: 3200,
  },

  "sql-formatter": {
    slug: "sql-formatter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Incorrect SQL syntax",
      "Missing semicolons",
      "Unbalanced parentheses",
      "Reserved word conflicts",
      "Inconsistent casing",
    ],
    useCases: [
      "Format ChatGPT SQL queries",
      "Clean Claude-generated stored procedures",
      "Validate Copilot database migrations",
    ],
    keywords: [
      "chatgpt sql formatter",
      "ai sql query fix",
      "claude sql syntax",
      "format ai database query",
    ],
    searchVolume: 4100,
  },

  "regex-tester": {
    slug: "regex-tester",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Unescaped special characters",
      "Greedy vs lazy quantifiers",
      "Catastrophic backtracking",
      "Incorrect character classes",
    ],
    useCases: [
      "Test ChatGPT regex patterns",
      "Validate AI-generated data validation",
      "Debug Claude regex suggestions",
    ],
    keywords: [
      "chatgpt regex tester",
      "ai regex validator",
      "test claude regex",
      "ai pattern matching",
    ],
    searchVolume: 2800,
  },

  "base64-converter": {
    slug: "base64-converter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Padding issues",
      "URL-safe vs standard encoding",
      "Unicode handling errors",
      "Line break inconsistencies",
    ],
    useCases: [
      "Decode AI-generated encoded strings",
      "Encode data for API requests",
      "Fix ChatGPT base64 output",
    ],
    keywords: [
      "ai base64 decoder",
      "chatgpt encode base64",
      "decode ai string",
      "base64 converter offline",
    ],
    searchVolume: 2100,
  },

  "url-encoder": {
    slug: "url-encoder",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Double encoding",
      "Space vs plus sign",
      "Special character handling",
      "Query string formatting",
    ],
    useCases: [
      "Encode AI-generated URL parameters",
      "Fix ChatGPT URL escaping",
      "Validate query strings",
    ],
    keywords: ["ai url encoder", "chatgpt url fix", "encode ai parameters"],
    searchVolume: 1500,
  },

  "hash-generator": {
    slug: "hash-generator",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Wrong algorithm selection",
      "Encoding mismatches",
      "Salt handling issues",
    ],
    useCases: [
      "Generate hashes for AI-created passwords",
      "Verify file integrity",
      "Create checksums offline",
    ],
    keywords: [
      "ai hash generator",
      "secure hash offline",
      "md5 sha256 generator",
    ],
    searchVolume: 1800,
  },

  "diff-checker": {
    slug: "diff-checker",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Whitespace differences",
      "Line ending mismatches",
      "Encoding discrepancies",
    ],
    useCases: [
      "Compare AI refactored code",
      "Review ChatGPT code changes",
      "Audit Copilot suggestions",
    ],
    keywords: [
      "compare ai code changes",
      "chatgpt diff tool",
      "ai code review",
    ],
    searchVolume: 2400,
  },

  "markdown-preview": {
    slug: "markdown-preview",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Incorrect heading levels",
      "Broken link syntax",
      "Code block language issues",
      "List formatting problems",
    ],
    useCases: [
      "Preview ChatGPT README files",
      "Validate AI documentation",
      "Check Claude markdown output",
    ],
    keywords: [
      "ai markdown preview",
      "chatgpt readme validator",
      "preview ai documentation",
    ],
    searchVolume: 1200,
  },

  "html-entity": {
    slug: "html-entity",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Unescaped HTML characters",
      "Double encoding",
      "Missing entity semicolons",
    ],
    useCases: [
      "Encode AI-generated HTML content",
      "Fix XSS in ChatGPT output",
      "Sanitize Claude HTML",
    ],
    keywords: [
      "ai html encoder",
      "escape chatgpt html",
      "html entity converter",
    ],
    searchVolume: 900,
  },

  "css-minifier": {
    slug: "css-minifier",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Invalid CSS syntax",
      "Vendor prefix issues",
      "Selector specificity problems",
    ],
    useCases: [
      "Minify AI-generated styles",
      "Optimize ChatGPT CSS",
      "Compress Copilot stylesheets",
    ],
    keywords: ["ai css minifier", "optimize chatgpt css", "compress ai styles"],
    searchVolume: 800,
  },

  "prettier-playground": {
    slug: "prettier-playground",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Inconsistent formatting",
      "Mixed tabs/spaces",
      "Line length issues",
      "Bracket placement",
    ],
    useCases: [
      "Format ChatGPT code output",
      "Standardize AI code style",
      "Clean Copilot suggestions",
    ],
    keywords: [
      "format ai code",
      "chatgpt code formatter",
      "prettier ai output",
    ],
    searchVolume: 3500,
  },

  "json-to-typescript": {
    slug: "json-to-typescript",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Incorrect type inference",
      "Missing optional properties",
      "Any type overuse",
      "Union type issues",
    ],
    useCases: [
      "Convert ChatGPT JSON to types",
      "Generate types from AI API responses",
      "Type-safe AI data structures",
    ],
    keywords: [
      "ai json to typescript",
      "chatgpt type generator",
      "convert ai json types",
    ],
    searchVolume: 2200,
  },

  "cron-parser": {
    slug: "cron-parser",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Invalid cron syntax",
      "Day-of-week confusion",
      "Timezone issues",
      "Special character misuse",
    ],
    useCases: [
      "Validate ChatGPT cron expressions",
      "Test AI-generated schedules",
      "Debug Claude cron jobs",
    ],
    keywords: [
      "ai cron validator",
      "chatgpt cron expression",
      "test ai scheduler",
    ],
    searchVolume: 1100,
  },

  "uuid-generator": {
    slug: "uuid-generator",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Invalid UUID format",
      "Version confusion",
      "Duplicate generation",
    ],
    useCases: [
      "Generate UUIDs for AI databases",
      "Validate ChatGPT ID formats",
      "Create unique identifiers offline",
    ],
    keywords: [
      "ai uuid generator",
      "offline uuid creator",
      "secure id generator",
    ],
    searchVolume: 1400,
  },

  "url-parser": {
    slug: "url-parser",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Malformed URLs",
      "Missing protocol",
      "Query string parsing",
      "Fragment handling",
    ],
    useCases: [
      "Parse AI-generated URLs",
      "Debug ChatGPT API endpoints",
      "Validate Claude URL structures",
    ],
    keywords: ["ai url parser", "chatgpt url analyzer", "parse ai endpoints"],
    searchVolume: 700,
  },

  // ============================================================
  // Text & Code Tools (6개 추가)
  // ============================================================

  "unix-timestamp": {
    slug: "unix-timestamp",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Milliseconds vs seconds confusion",
      "Timezone handling errors",
      "Date parsing format mismatch",
      "Epoch overflow issues",
    ],
    useCases: [
      "Convert ChatGPT timestamp outputs",
      "Debug AI-generated date calculations",
      "Validate Claude time zone handling",
    ],
    keywords: [
      "ai timestamp converter",
      "chatgpt unix time",
      "convert ai date to timestamp",
      "fix ai epoch time",
    ],
    searchVolume: 2800,
  },

  "base-converter": {
    slug: "base-converter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Binary to decimal mistakes",
      "Hex color code errors",
      "Octal prefix confusion",
      "Large number overflow",
    ],
    useCases: [
      "Convert ChatGPT number outputs",
      "Verify AI binary calculations",
      "Debug hex color conversions",
    ],
    keywords: [
      "ai number converter",
      "chatgpt binary hex",
      "convert ai base numbers",
      "fix ai number format",
    ],
    searchVolume: 1200,
  },

  "lorem-generator": {
    slug: "lorem-generator",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Inconsistent placeholder lengths",
      "Wrong language characters",
      "Missing paragraph structure",
    ],
    useCases: [
      "Generate placeholder text for AI mockups",
      "Replace ChatGPT dummy content",
      "Create consistent test data",
    ],
    keywords: [
      "ai lorem generator",
      "chatgpt placeholder text",
      "ai dummy content",
      "generate test text",
    ],
    searchVolume: 900,
  },

  "text-case-converter": {
    slug: "text-case-converter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "camelCase vs snake_case confusion",
      "CONSTANT_CASE mistakes",
      "PascalCase inconsistencies",
      "kebab-case in wrong contexts",
    ],
    useCases: [
      "Fix ChatGPT variable naming",
      "Convert AI constant names",
      "Standardize Copilot identifiers",
    ],
    keywords: [
      "ai case converter",
      "chatgpt variable naming",
      "fix ai camelcase",
      "convert ai text case",
    ],
    searchVolume: 1800,
  },

  "curl-builder": {
    slug: "curl-builder",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Missing authentication headers",
      "Wrong content-type",
      "Improperly escaped quotes",
      "Invalid JSON body format",
    ],
    useCases: [
      "Build cURL from ChatGPT API examples",
      "Debug Claude HTTP request suggestions",
      "Convert AI fetch code to cURL",
    ],
    keywords: [
      "ai curl generator",
      "chatgpt curl command",
      "build curl from ai",
      "convert ai api request",
    ],
    searchVolume: 2100,
  },

  "ua-parser": {
    slug: "ua-parser",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Outdated browser detection",
      "Mobile vs desktop misidentification",
      "Bot detection false positives",
    ],
    useCases: [
      "Parse AI-generated user agent strings",
      "Debug ChatGPT browser detection code",
      "Validate device targeting logic",
    ],
    keywords: [
      "ai user agent parser",
      "chatgpt ua string",
      "parse browser string",
      "detect device ai",
    ],
    searchVolume: 600,
  },

  // ============================================================
  // Media & Design Tools (10개 추가)
  // ============================================================

  "image-resizer": {
    slug: "image-resizer",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Wrong aspect ratio calculations",
      "Quality degradation",
      "Missing responsive breakpoints",
      "Incorrect file format",
    ],
    useCases: [
      "Resize images for AI-suggested dimensions",
      "Create thumbnails for ChatGPT mockups",
      "Optimize images per AI guidelines",
    ],
    keywords: [
      "ai image resize",
      "chatgpt image dimensions",
      "resize for ai project",
      "optimize image size",
    ],
    searchVolume: 3500,
  },

  "app-icon-generator": {
    slug: "app-icon-generator",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Wrong icon sizes for platforms",
      "Missing required formats",
      "Transparency issues",
      "Resolution mismatch",
    ],
    useCases: [
      "Generate icons from AI designs",
      "Create app icons for ChatGPT projects",
      "Export all required icon sizes",
    ],
    keywords: [
      "ai app icon generator",
      "chatgpt icon sizes",
      "generate app icons",
      "favicon generator ai",
    ],
    searchVolume: 1400,
  },

  "qr-generator": {
    slug: "qr-generator",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "URL encoding problems",
      "Size too small for scanning",
      "Low error correction level",
      "Invalid data format",
    ],
    useCases: [
      "Generate QR codes for AI URLs",
      "Create scannable codes from ChatGPT data",
      "Embed QR in AI presentations",
    ],
    keywords: [
      "ai qr generator",
      "chatgpt qr code",
      "generate qr from ai",
      "qr code maker offline",
    ],
    searchVolume: 2200,
  },

  "color-picker": {
    slug: "color-picker",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "RGB vs HEX confusion",
      "HSL conversion errors",
      "Opacity/alpha mistakes",
      "Color contrast issues",
    ],
    useCases: [
      "Convert ChatGPT color codes",
      "Extract colors from AI palettes",
      "Verify accessibility contrast",
    ],
    keywords: [
      "ai color picker",
      "chatgpt hex color",
      "convert ai colors",
      "color code converter",
    ],
    searchVolume: 2600,
  },

  "box-shadow": {
    slug: "box-shadow",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Incorrect spread vs blur values",
      "Missing color alpha",
      "Wrong offset directions",
      "Browser compatibility issues",
    ],
    useCases: [
      "Customize ChatGPT shadow suggestions",
      "Fine-tune AI-generated CSS shadows",
      "Preview Claude shadow code",
    ],
    keywords: [
      "ai box shadow generator",
      "chatgpt css shadow",
      "edit ai shadow code",
      "shadow generator tool",
    ],
    searchVolume: 1100,
  },

  "gradient-generator": {
    slug: "gradient-generator",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Wrong gradient direction",
      "Color stop position errors",
      "Missing fallback colors",
      "Radial vs linear confusion",
    ],
    useCases: [
      "Edit ChatGPT gradient code",
      "Preview AI color transitions",
      "Generate CSS from AI descriptions",
    ],
    keywords: [
      "ai gradient generator",
      "chatgpt css gradient",
      "edit ai gradient",
      "gradient css maker",
    ],
    searchVolume: 1500,
  },

  "svg-optimizer": {
    slug: "svg-optimizer",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Verbose path data",
      "Unnecessary metadata",
      "Inline styles bloat",
      "Missing viewBox",
    ],
    useCases: [
      "Optimize ChatGPT SVG output",
      "Clean AI-generated icons",
      "Reduce Claude SVG file size",
    ],
    keywords: [
      "ai svg optimizer",
      "chatgpt svg cleaner",
      "optimize ai svg",
      "svg minifier tool",
    ],
    searchVolume: 1300,
  },

  "bg-remover": {
    slug: "bg-remover",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Edge artifacts",
      "Transparency not preserved",
      "Hair/fine detail loss",
      "Wrong output format",
    ],
    useCases: [
      "Remove background from AI images",
      "Create transparent assets",
      "Prepare images for AI compositions",
    ],
    keywords: [
      "ai background remover",
      "remove bg free",
      "transparent image maker",
      "ai cutout tool",
    ],
    searchVolume: 8500,
  },

  "og-generator": {
    slug: "og-generator",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Wrong dimensions for platforms",
      "Text overflow",
      "Poor mobile preview",
      "Missing required tags",
    ],
    useCases: [
      "Create OG images for AI content",
      "Generate social previews",
      "Design ChatGPT blog thumbnails",
    ],
    keywords: [
      "ai og image generator",
      "chatgpt social image",
      "og image maker",
      "social preview generator",
    ],
    searchVolume: 2000,
  },

  "image-converter": {
    slug: "image-converter",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Quality loss in conversion",
      "Wrong color profile",
      "Metadata stripping issues",
      "Format compatibility",
    ],
    useCases: [
      "Convert AI-generated images",
      "Change format for web optimization",
      "Batch convert project assets",
    ],
    keywords: [
      "ai image converter",
      "convert png to webp",
      "image format changer",
      "batch image converter",
    ],
    searchVolume: 4200,
  },

  // ============================================================
  // SEO & Web Tools (6개 추가)
  // ============================================================

  "meta-generator": {
    slug: "meta-generator",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Title length too long",
      "Missing og:image",
      "Duplicate meta tags",
      "Wrong charset encoding",
    ],
    useCases: [
      "Generate meta tags from AI descriptions",
      "Complete ChatGPT HTML head",
      "SEO optimize AI content",
    ],
    keywords: [
      "ai meta tag generator",
      "chatgpt seo tags",
      "generate meta from ai",
      "seo tag maker",
    ],
    searchVolume: 1900,
  },

  "schema-generator": {
    slug: "schema-generator",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Invalid JSON-LD syntax",
      "Missing required properties",
      "Wrong schema type",
      "Deprecated schema fields",
    ],
    useCases: [
      "Generate schema from AI content",
      "Fix ChatGPT structured data",
      "Validate Claude JSON-LD",
    ],
    keywords: [
      "ai schema generator",
      "chatgpt json-ld",
      "structured data maker",
      "schema markup tool",
    ],
    searchVolume: 2400,
  },

  "sitemap-generator": {
    slug: "sitemap-generator",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Invalid XML format",
      "Wrong lastmod dates",
      "Missing priority values",
      "URL encoding issues",
    ],
    useCases: [
      "Generate sitemap from AI URL list",
      "Validate ChatGPT sitemap output",
      "Create XML sitemap offline",
    ],
    keywords: [
      "ai sitemap generator",
      "chatgpt sitemap xml",
      "generate sitemap tool",
      "xml sitemap maker",
    ],
    searchVolume: 1600,
  },

  "meta-tag-analyzer": {
    slug: "meta-tag-analyzer",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Missing critical tags",
      "Duplicate content issues",
      "Invalid og:url format",
      "Twitter card errors",
    ],
    useCases: [
      "Analyze AI-built HTML pages",
      "Audit ChatGPT meta tags",
      "Check SEO completeness",
    ],
    keywords: [
      "ai meta analyzer",
      "check chatgpt seo",
      "meta tag checker",
      "seo audit tool",
    ],
    searchVolume: 1100,
  },

  "robots-generator": {
    slug: "robots-generator",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Incorrect disallow syntax",
      "Missing user-agent",
      "Wildcard mistakes",
      "Sitemap reference errors",
    ],
    useCases: [
      "Generate robots.txt from AI rules",
      "Fix ChatGPT robots directives",
      "Create crawler instructions",
    ],
    keywords: [
      "ai robots generator",
      "chatgpt robots.txt",
      "robots file maker",
      "crawler rules tool",
    ],
    searchVolume: 800,
  },

  "serp-preview": {
    slug: "serp-preview",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Title truncation",
      "Description cut-off",
      "URL display issues",
      "Rich snippet errors",
    ],
    useCases: [
      "Preview AI-written SEO content",
      "Check ChatGPT title/description",
      "Optimize search appearance",
    ],
    keywords: [
      "ai serp preview",
      "chatgpt google preview",
      "seo preview tool",
      "search result checker",
    ],
    searchVolume: 1200,
  },

  // ============================================================
  // Utility Tools (6개 추가)
  // ============================================================

  "video-compressor": {
    slug: "video-compressor",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Quality vs size tradeoff",
      "Wrong codec selection",
      "Audio sync issues",
      "Resolution mistakes",
    ],
    useCases: [
      "Compress videos for AI projects",
      "Optimize AI-generated content",
      "Reduce file size for web",
    ],
    keywords: [
      "ai video compressor",
      "compress video online",
      "reduce video size",
      "video optimizer tool",
    ],
    searchVolume: 5200,
  },

  "pdf-toolkit": {
    slug: "pdf-toolkit",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Merge order issues",
      "Page rotation errors",
      "Compression quality loss",
      "Font embedding problems",
    ],
    useCases: [
      "Process AI-generated PDFs",
      "Merge ChatGPT document outputs",
      "Compress PDF reports",
    ],
    keywords: [
      "ai pdf tool",
      "merge pdf online",
      "compress pdf free",
      "pdf editor tool",
    ],
    searchVolume: 6800,
  },

  "ocr-scanner": {
    slug: "ocr-scanner",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Character recognition errors",
      "Layout preservation issues",
      "Language detection failures",
      "Handwriting misreads",
    ],
    useCases: [
      "Extract text for AI processing",
      "Digitize documents for ChatGPT",
      "Convert images to editable text",
    ],
    keywords: [
      "ai ocr scanner",
      "image to text ai",
      "ocr online free",
      "text extraction tool",
    ],
    searchVolume: 7500,
  },

  "headline-analyzer": {
    slug: "headline-analyzer",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Clickbait detection",
      "Emotional word overuse",
      "Length optimization",
      "Power word placement",
    ],
    useCases: [
      "Analyze ChatGPT headlines",
      "Optimize AI-generated titles",
      "Improve content CTR",
    ],
    keywords: [
      "ai headline analyzer",
      "chatgpt title checker",
      "headline score tool",
      "title optimizer",
    ],
    searchVolume: 1700,
  },

  "css-to-tailwind": {
    slug: "css-to-tailwind",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Unsupported CSS properties",
      "Complex selector conversion",
      "Media query handling",
      "Custom value approximation",
    ],
    useCases: [
      "Convert ChatGPT CSS to Tailwind",
      "Migrate AI styles to utility classes",
      "Modernize legacy CSS code",
    ],
    keywords: [
      "ai css to tailwind",
      "chatgpt tailwind converter",
      "convert css utility",
      "tailwind migration tool",
    ],
    searchVolume: 3100,
  },

  "share-as-image": {
    slug: "share-as-image",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Text overflow in image",
      "Resolution too low",
      "Font rendering issues",
      "Background transparency",
    ],
    useCases: [
      "Share AI code snippets",
      "Create ChatGPT output images",
      "Generate shareable quotes",
    ],
    keywords: [
      "ai code to image",
      "share chatgpt output",
      "code screenshot maker",
      "text to image tool",
    ],
    searchVolume: 2300,
  },
};

/**
 * Helper Functions
 */
export function getAICompatibleTools(): AICompatibleTool[] {
  return Object.keys(aiContextTools) as AICompatibleTool[];
}

export function getAIContextMeta(
  slug: AICompatibleTool,
): AIContextMeta | undefined {
  return aiContextTools[slug];
}

export function getAISourceBranding(source: AISource): AISourceBranding {
  return aiSources[source];
}

export function getAllAISources(): AISource[] {
  return Object.keys(aiSources) as AISource[];
}
