import type {
  AISource,
  AISourceBranding,
  AIContextMeta,
  AICompatibleTool,
} from "./types";

/**
 * AI Source Branding
 */
export const aiSources: Record<AISource, AISourceBranding> = {
  "ai-generated": {
    id: "ai-generated",
    name: "AI-Generated",
    color: "from-purple-500 to-pink-500",
    description: "Code generated by any AI assistant",
  },
  chatgpt: {
    id: "chatgpt",
    name: "ChatGPT",
    color: "from-emerald-500 to-teal-500",
    description: "OpenAI's ChatGPT code output",
  },
  claude: {
    id: "claude",
    name: "Claude",
    color: "from-orange-500 to-amber-500",
    description: "Anthropic's Claude code output",
  },
  copilot: {
    id: "copilot",
    name: "GitHub Copilot",
    color: "from-gray-600 to-gray-800",
    description: "GitHub Copilot suggestions",
  },
  gemini: {
    id: "gemini",
    name: "Gemini",
    color: "from-blue-500 to-indigo-500",
    description: "Google Gemini code output",
  },
  cursor: {
    id: "cursor",
    name: "Cursor AI",
    color: "from-violet-500 to-purple-600",
    description: "Cursor IDE AI suggestions",
  },
};

/**
 * AI-Compatible Tools with Context Metadata
 */
export const aiContextTools: Record<AICompatibleTool, AIContextMeta> = {
  "json-formatter": {
    slug: "json-formatter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "gemini"],
    commonErrors: [
      "Unexpected token in JSON",
      "Single quotes instead of double quotes",
      "Trailing comma in object/array",
      "Unescaped special characters",
      "Missing property quotes",
    ],
    useCases: [
      "Validate ChatGPT-generated API responses",
      "Fix Claude's JSON configuration files",
      "Clean up Copilot's data structures",
    ],
    keywords: [
      "chatgpt json fix",
      "ai json validator",
      "claude json formatter",
      "fix ai json error",
      "copilot json syntax",
    ],
    searchVolume: 8500,
  },

  "jwt-decoder": {
    slug: "jwt-decoder",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Invalid JWT format",
      "Missing JWT segments",
      "Base64 encoding issues",
      "Expired token not detected",
    ],
    useCases: [
      "Decode ChatGPT-generated auth tokens",
      "Verify AI-suggested JWT structures",
      "Debug authentication flows",
    ],
    keywords: [
      "ai jwt decoder",
      "chatgpt jwt token",
      "validate ai auth token",
      "decode jwt online secure",
    ],
    searchVolume: 3200,
  },

  "sql-formatter": {
    slug: "sql-formatter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Incorrect SQL syntax",
      "Missing semicolons",
      "Unbalanced parentheses",
      "Reserved word conflicts",
      "Inconsistent casing",
    ],
    useCases: [
      "Format ChatGPT SQL queries",
      "Clean Claude-generated stored procedures",
      "Validate Copilot database migrations",
    ],
    keywords: [
      "chatgpt sql formatter",
      "ai sql query fix",
      "claude sql syntax",
      "format ai database query",
    ],
    searchVolume: 4100,
  },

  "regex-tester": {
    slug: "regex-tester",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Unescaped special characters",
      "Greedy vs lazy quantifiers",
      "Catastrophic backtracking",
      "Incorrect character classes",
    ],
    useCases: [
      "Test ChatGPT regex patterns",
      "Validate AI-generated data validation",
      "Debug Claude regex suggestions",
    ],
    keywords: [
      "chatgpt regex tester",
      "ai regex validator",
      "test claude regex",
      "ai pattern matching",
    ],
    searchVolume: 2800,
  },

  "base64-converter": {
    slug: "base64-converter",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Padding issues",
      "URL-safe vs standard encoding",
      "Unicode handling errors",
      "Line break inconsistencies",
    ],
    useCases: [
      "Decode AI-generated encoded strings",
      "Encode data for API requests",
      "Fix ChatGPT base64 output",
    ],
    keywords: [
      "ai base64 decoder",
      "chatgpt encode base64",
      "decode ai string",
      "base64 converter offline",
    ],
    searchVolume: 2100,
  },

  "url-encoder": {
    slug: "url-encoder",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Double encoding",
      "Space vs plus sign",
      "Special character handling",
      "Query string formatting",
    ],
    useCases: [
      "Encode AI-generated URL parameters",
      "Fix ChatGPT URL escaping",
      "Validate query strings",
    ],
    keywords: ["ai url encoder", "chatgpt url fix", "encode ai parameters"],
    searchVolume: 1500,
  },

  "hash-generator": {
    slug: "hash-generator",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Wrong algorithm selection",
      "Encoding mismatches",
      "Salt handling issues",
    ],
    useCases: [
      "Generate hashes for AI-created passwords",
      "Verify file integrity",
      "Create checksums offline",
    ],
    keywords: [
      "ai hash generator",
      "secure hash offline",
      "md5 sha256 generator",
    ],
    searchVolume: 1800,
  },

  "diff-checker": {
    slug: "diff-checker",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Whitespace differences",
      "Line ending mismatches",
      "Encoding discrepancies",
    ],
    useCases: [
      "Compare AI refactored code",
      "Review ChatGPT code changes",
      "Audit Copilot suggestions",
    ],
    keywords: [
      "compare ai code changes",
      "chatgpt diff tool",
      "ai code review",
    ],
    searchVolume: 2400,
  },

  "markdown-preview": {
    slug: "markdown-preview",
    aiSources: ["ai-generated", "chatgpt", "claude", "gemini"],
    commonErrors: [
      "Incorrect heading levels",
      "Broken link syntax",
      "Code block language issues",
      "List formatting problems",
    ],
    useCases: [
      "Preview ChatGPT README files",
      "Validate AI documentation",
      "Check Claude markdown output",
    ],
    keywords: [
      "ai markdown preview",
      "chatgpt readme validator",
      "preview ai documentation",
    ],
    searchVolume: 1200,
  },

  "html-entity": {
    slug: "html-entity",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Unescaped HTML characters",
      "Double encoding",
      "Missing entity semicolons",
    ],
    useCases: [
      "Encode AI-generated HTML content",
      "Fix XSS in ChatGPT output",
      "Sanitize Claude HTML",
    ],
    keywords: [
      "ai html encoder",
      "escape chatgpt html",
      "html entity converter",
    ],
    searchVolume: 900,
  },

  "css-minifier": {
    slug: "css-minifier",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Invalid CSS syntax",
      "Vendor prefix issues",
      "Selector specificity problems",
    ],
    useCases: [
      "Minify AI-generated styles",
      "Optimize ChatGPT CSS",
      "Compress Copilot stylesheets",
    ],
    keywords: ["ai css minifier", "optimize chatgpt css", "compress ai styles"],
    searchVolume: 800,
  },

  "prettier-playground": {
    slug: "prettier-playground",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot", "cursor"],
    commonErrors: [
      "Inconsistent formatting",
      "Mixed tabs/spaces",
      "Line length issues",
      "Bracket placement",
    ],
    useCases: [
      "Format ChatGPT code output",
      "Standardize AI code style",
      "Clean Copilot suggestions",
    ],
    keywords: [
      "format ai code",
      "chatgpt code formatter",
      "prettier ai output",
    ],
    searchVolume: 3500,
  },

  "json-to-typescript": {
    slug: "json-to-typescript",
    aiSources: ["ai-generated", "chatgpt", "claude", "copilot"],
    commonErrors: [
      "Incorrect type inference",
      "Missing optional properties",
      "Any type overuse",
      "Union type issues",
    ],
    useCases: [
      "Convert ChatGPT JSON to types",
      "Generate types from AI API responses",
      "Type-safe AI data structures",
    ],
    keywords: [
      "ai json to typescript",
      "chatgpt type generator",
      "convert ai json types",
    ],
    searchVolume: 2200,
  },

  "cron-parser": {
    slug: "cron-parser",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Invalid cron syntax",
      "Day-of-week confusion",
      "Timezone issues",
      "Special character misuse",
    ],
    useCases: [
      "Validate ChatGPT cron expressions",
      "Test AI-generated schedules",
      "Debug Claude cron jobs",
    ],
    keywords: [
      "ai cron validator",
      "chatgpt cron expression",
      "test ai scheduler",
    ],
    searchVolume: 1100,
  },

  "uuid-generator": {
    slug: "uuid-generator",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Invalid UUID format",
      "Version confusion",
      "Duplicate generation",
    ],
    useCases: [
      "Generate UUIDs for AI databases",
      "Validate ChatGPT ID formats",
      "Create unique identifiers offline",
    ],
    keywords: [
      "ai uuid generator",
      "offline uuid creator",
      "secure id generator",
    ],
    searchVolume: 1400,
  },

  "url-parser": {
    slug: "url-parser",
    aiSources: ["ai-generated", "chatgpt", "claude"],
    commonErrors: [
      "Malformed URLs",
      "Missing protocol",
      "Query string parsing",
      "Fragment handling",
    ],
    useCases: [
      "Parse AI-generated URLs",
      "Debug ChatGPT API endpoints",
      "Validate Claude URL structures",
    ],
    keywords: ["ai url parser", "chatgpt url analyzer", "parse ai endpoints"],
    searchVolume: 700,
  },
};

/**
 * Helper Functions
 */
export function getAICompatibleTools(): AICompatibleTool[] {
  return Object.keys(aiContextTools) as AICompatibleTool[];
}

export function getAIContextMeta(
  slug: AICompatibleTool,
): AIContextMeta | undefined {
  return aiContextTools[slug];
}

export function getAISourceBranding(source: AISource): AISourceBranding {
  return aiSources[source];
}

export function getAllAISources(): AISource[] {
  return Object.keys(aiSources) as AISource[];
}
