/**
 * Tool type definitions (shared layer)
 * These types are used across all layers including shared hooks
 */

export type ToolCategory = "text" | "media" | "security" | "converters";

export type ToolSlug =
  | "json-formatter"
  | "jwt-decoder"
  | "image-resizer"
  | "unix-timestamp"
  | "base64-converter"
  | "app-icon-generator"
  | "qr-generator"
  | "color-picker"
  | "url-parser"
  | "uuid-generator"
  | "base-converter"
  | "hash-generator"
  | "sql-formatter"
  | "cron-parser"
  | "markdown-preview"
  | "diff-checker"
  | "lorem-generator"
  | "url-encoder"
  | "html-entity"
  | "box-shadow"
  | "gradient-generator"
  | "ua-parser"
  | "regex-tester"
  | "meta-generator"
  | "curl-builder"
  | "svg-optimizer"
  | "css-to-tailwind"
  | "prettier-playground"
  | "json-to-typescript"
  | "css-minifier"
  | "text-case-converter"
  | "video-compressor"
  | "pdf-toolkit"
  | "ocr-scanner"
  | "schema-generator"
  | "headline-analyzer"
  | "bg-remover"
  | "og-generator"
  | "image-converter"
  | "sitemap-generator"
  | "meta-tag-analyzer"
  | "robots-generator"
  | "serp-preview"
  | "share-as-image"
  | "token-counter";
